apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-py-app
  labels:
    app: sample-py-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-py-app
  template:
    metadata:
      labels:
        app: sample-py-app
    spec:
      containers:
      - name: py-app-sample
        image: yogi404/python-sample-app-demo:v1
        ports:
        - containerPort: 8000